name: "Refresh result analysis"

env:
  AWS_REGION: us-west-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::798883743502:role/github-actions-ec2-provisioner
  AWS_LOGS_BUCKET_NAME: data-api-nb-test-logs
  ATLASSIAN_EMAIL: ${{ secrets.ATLASSIAN_EMAIL }}
  ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
  ATLASSIAN_BASE_URL: ${{ secrets.ATLASSIAN_BASE_URL }}
  ATLASSIAN_PAGE_ID: ${{ secrets.ATLASSIAN_PAGE_ID }}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  run-analytics-and-store:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r analytics/requirements.txt

      - name: Create directories
        run: |
          mkdir -p input_logs
          mkdir -p output_analysis

      - name: Fetch raw logs from S3
        run: |
          aws s3 cp s3://${{ env.AWS_LOGS_BUCKET_NAME }}/logs/ input_logs/ --recursive

      - name: Run Python script (with Atlassian integration)
        if: env.ATLASSIAN_API_TOKEN != ''
        run: |
          python analytics.py \
            --input_dir ../input_logs \
            --output_dir ../output_analysis \
            --atlassian
        working-directory: analytics

      - name: Run Python script (no Atlassian integration)
        if: env.ATLASSIAN_API_TOKEN == ''
        run: |
          python analytics.py \
            --input_dir ../input_logs \
            --output_dir ../output_analysis
        working-directory: analytics

      - name: Store analysis results to S3
        run: |
          aws s3 sync output_analysis/ s3://${{ env.AWS_LOGS_BUCKET_NAME }}/analysis --delete
