name: Pull image from ECR
on:
  workflow_dispatch:
  push:
    branches: [ main ]   # or whatever you allowed in the trust policy

permissions:
  id-token: write          # required for OIDC
  contents: read           # required for actions/checkout if you use it

env:
  AWS_REGION: eu-west-1            # set your region
  AWS_ACCOUNT_ID: "798883743502"   # set your account
  ECR_REPOSITORY: "my-repo"         # set your repo
  IMAGE_TAG: "v1.2.3"              # or 'latest' etc.
  ECR_REGISTRY: "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/EC2_test_puller_role
          aws-region: ${{ env.AWS_REGION }}

      # Either of the following works. Pick one.

      # Option 1: Official ECR login action
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Option 2: Docker login action (explicit)
      # - name: Login to ECR (docker/login-action)
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.ECR_REGISTRY }}
      #     username: AWS
      #     password: ${{ steps.configure.outputs.aws-session-token }}

      - name: Pull the image
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
